### ISSUE TITLE
Wrong Directory

### ISSUE THREAD

**Issue by reverendj1** [mr-chrome/elegoo-cura-dots#1]
Thanks for doing this. I just installed Cura 4.8.0 via the thopiekar PPA on Ubuntu 20.04. The path I had to put the files was actually `~/.local/share/cura/4.8`. So users may have to include their version number in the path.

**Comment by gicrisf** [comment]
Hi @reverendj1, thanks for submitting this. 
I'm going to update the Readme file with your suggestion very soon.
